import {BuyTabState, DashboardState, InitState} from './type';

export const initDashboardState: DashboardState = {
  dashboard: {
    listRecentlyCosmetics: [
      {
        blockchainId: 0,
        id: '643f67a45a8158f5a24aa8d3',
        cosmeticInfo: {status: 20, typeId: 15, type: 1, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '643f67a45a8158f5a24aa8d3',
        refType: 2,
        tokenId: 16818769055049,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0x96a928e9833bf0fe790f8247b4ce4f4fd2f26d53',
        userAddress: '0x96a928e9833bf0fe790f8247b4ce4f4fd2f26d53',
        cosmeticRarity: 1,
        cosmeticType: 1,
        cosmeticName: '',
        timestamp: 1681966175077,
      },
      {
        blockchainId: 0,
        id: '643f67ac5a8158f5a24aa8d6',
        cosmeticInfo: {status: 20, typeId: 20017, type: 2, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '643f67ac5a8158f5a24aa8d6',
        refType: 2,
        tokenId: 16818769135050,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 100000,
          },
        },
        ownerAddress: '0x5df2e23857ae2516cbd288bc6d547ac508318db6',
        userAddress: '0x5df2e23857ae2516cbd288bc6d547ac508318db6',
        cosmeticRarity: 1,
        cosmeticType: 2,
        cosmeticName: '',
        timestamp: 1681876975486,
      },
      {
        blockchainId: 0,
        id: '643f67a45a8158f5a24aa8d3',
        cosmeticInfo: {status: 20, typeId: 15, type: 1, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '643f67a45a8158f5a24aa8d3',
        refType: 2,
        tokenId: 16818769055049,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0x5df2e23857ae2516cbd288bc6d547ac508318db6',
        userAddress: '0x5df2e23857ae2516cbd288bc6d547ac508318db6',
        cosmeticRarity: 1,
        cosmeticType: 1,
        cosmeticName: '',
        timestamp: 1681876955039,
      },
      {
        blockchainId: 0,
        id: '62cead8abdd001d7a8a85196',
        cosmeticInfo: {status: 20, typeId: 20016, type: 2, rarity: 2},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '62cead8abdd001d7a8a85196',
        refType: 2,
        tokenId: 16577120139731,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0xb8450814213bc27d8f6d368d09feeda8b6cd1d63',
        userAddress: '0xb8450814213bc27d8f6d368d09feeda8b6cd1d63',
        cosmeticRarity: 2,
        cosmeticType: 2,
        cosmeticName: '',
        timestamp: 1680504378286,
      },
      {
        blockchainId: 0,
        id: '62cead83bdd001d7a8a85192',
        cosmeticInfo: {status: 20, typeId: 40003, type: 4, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '62cead83bdd001d7a8a85192',
        refType: 2,
        tokenId: 16577120069727,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0xb8450814213bc27d8f6d368d09feeda8b6cd1d63',
        userAddress: '0xb8450814213bc27d8f6d368d09feeda8b6cd1d63',
        cosmeticRarity: 1,
        cosmeticType: 4,
        cosmeticName: 'Blue Shark',
        timestamp: 1680504132470,
      },
      {
        blockchainId: 0,
        id: '63083edbfe0fb1655afd3b34',
        cosmeticInfo: {status: 20, typeId: 40003, type: 4, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '63083edbfe0fb1655afd3b34',
        refType: 2,
        tokenId: 16614847664726,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0x7536e76e2512f6ca7a2dcf93565c8185bbbb32e9',
        userAddress: '0x7536e76e2512f6ca7a2dcf93565c8185bbbb32e9',
        cosmeticRarity: 1,
        cosmeticType: 4,
        cosmeticName: 'Blue Shark',
        timestamp: 1675926563753,
      },
      {
        blockchainId: 0,
        id: '62e09d5d6fff0fa830b5ff53',
        cosmeticInfo: {status: 20, typeId: 20017, type: 2, rarity: 1},
        createdAt: '',
        lastModified: '0001-01-01T00:00:00Z',
        refId: '62e09d5d6fff0fa830b5ff53',
        refType: 2,
        tokenId: 16588875201275,
        saleInfo: {
          price: {
            decimals: 8,
            name: 'THC',
            type: 11,
            value: 1000000000000,
          },
        },
        ownerAddress: '0x7536e76e2512f6ca7a2dcf93565c8185bbbb32e9',
        userAddress: '0x7536e76e2512f6ca7a2dcf93565c8185bbbb32e9',
        cosmeticRarity: 1,
        cosmeticType: 2,
        cosmeticName: '',
        timestamp: 1675140403681,
      },
    ],
  },
};
export const initBuyTabState: BuyTabState = {
  configSkin: [
    {
      id: 0,
      heroTypeId: 0,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/0.png',
      imageSmallAvatar: 'skin/smallavatar/0.png',
      imageFull: 'skin/full/0.png',
      model3D: 'skin/model3d/0.glb',
      scaleRatio: 1,
      cost: 333,
      name: "Earth's Hero",
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1,
      heroTypeId: 0,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/1.png',
      imageSmallAvatar: 'skin/smallavatar/1.png',
      imageFull: 'skin/full/1.png',
      model3D: 'skin/model3d/1.glb',
      scaleRatio: 1.1,
      cost: 333,
      name: 'Galaxy Ranger',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2,
      heroTypeId: 0,
      heroRarity: 0,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/2.png',
      imageSmallAvatar: 'skin/smallavatar/2.png',
      imageFull: 'skin/full/2.png',
      model3D: 'skin/model3d/2.glb',
      scaleRatio: 1.2,
      cost: 667,
      name: 'Anonymous',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 3,
      heroTypeId: 0,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/3.png',
      imageSmallAvatar: 'skin/smallavatar/3.png',
      imageFull: 'skin/full/3.png',
      model3D: 'skin/model3d/3.glb',
      scaleRatio: 1.2,
      cost: 667,
      name: 'Ultimate Striker',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 100,
      heroTypeId: 1,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/1000.png',
      imageSmallAvatar: 'skin/smallavatar/1000.png',
      imageFull: 'skin/full/1000.png',
      model3D: 'skin/model3d/1000.glb',
      scaleRatio: 1.7,
      cost: 333,
      name: 'Rogue Soldier',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 101,
      heroTypeId: 1,
      heroRarity: 0,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/1001.png',
      imageSmallAvatar: 'skin/smallavatar/1001.png',
      imageFull: 'skin/full/1001.png',
      model3D: 'skin/model3d/1001.glb',
      scaleRatio: 1.7,
      cost: 667,
      name: 'Exemplary Student',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 102,
      heroTypeId: 1,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/1002.png',
      imageSmallAvatar: 'skin/smallavatar/1002.png',
      imageFull: 'skin/full/1002.png',
      model3D: 'skin/model3d/1002.glb',
      scaleRatio: 1.7,
      cost: 1111,
      name: 'Lunar New Year',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 200,
      heroTypeId: 2,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/2000.png',
      imageSmallAvatar: 'skin/smallavatar/2000.png',
      imageFull: 'skin/full/2000.png',
      model3D: 'skin/model3d/2000.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'The Protective Gunner',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 201,
      heroTypeId: 2,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/2001.png',
      imageSmallAvatar: 'skin/smallavatar/2001.png',
      imageFull: 'skin/full/2001.png',
      model3D: 'skin/model3d/2001.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'Milk Cow',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 202,
      heroTypeId: 2,
      heroRarity: 0,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/2002.png',
      imageSmallAvatar: 'skin/smallavatar/2002.png',
      imageFull: 'skin/full/2002.png',
      model3D: 'skin/model3d/2002.glb',
      scaleRatio: 1.2,
      cost: 667,
      name: 'Titan',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 300,
      heroTypeId: 3,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/3000.png',
      imageSmallAvatar: 'skin/smallavatar/3000.png',
      imageFull: 'skin/full/3000.png',
      model3D: 'skin/model3d/3000.glb',
      scaleRatio: 1.2,
      cost: 1667,
      name: 'The Huntsman',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 301,
      heroTypeId: 3,
      heroRarity: 1,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/3001.png',
      imageSmallAvatar: 'skin/smallavatar/3001.png',
      imageFull: 'skin/full/3001.png',
      model3D: 'skin/model3d/3001.glb',
      scaleRatio: 1.2,
      cost: 5556,
      name: 'Lunar New Year',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 400,
      heroTypeId: 4,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/4000.png',
      imageSmallAvatar: 'skin/smallavatar/4000.png',
      imageFull: 'skin/full/4000.png',
      model3D: 'skin/model3d/4000.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Western Cowboy',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 401,
      heroTypeId: 4,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/4001.png',
      imageSmallAvatar: 'skin/smallavatar/4001.png',
      imageFull: 'skin/full/4001.png',
      model3D: 'skin/model3d/4001.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Los Muertos',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 402,
      heroTypeId: 4,
      heroRarity: 0,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/4002.png',
      imageSmallAvatar: 'skin/smallavatar/4002.png',
      imageFull: 'skin/full/4002.png',
      model3D: 'skin/model3d/4002.glb',
      scaleRatio: 1.3,
      cost: 667,
      name: 'Calvary General',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 500,
      heroTypeId: 5,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/5000.png',
      imageSmallAvatar: 'skin/smallavatar/5000.png',
      imageFull: 'skin/full/5000.png',
      model3D: 'skin/model3d/5000.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Rocket Master',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 501,
      heroTypeId: 5,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/5001.png',
      imageSmallAvatar: 'skin/smallavatar/5001.png',
      imageFull: 'skin/full/5001.png',
      model3D: 'skin/model3d/5001.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Spaceman',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 502,
      heroTypeId: 5,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/5002.png',
      imageSmallAvatar: 'skin/smallavatar/5002.png',
      imageFull: 'skin/full/5002.png',
      model3D: 'skin/model3d/5002.glb',
      scaleRatio: 1.2,
      cost: 1111,
      name: 'Lunar New Year',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 600,
      heroTypeId: 6,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/6000.png',
      imageSmallAvatar: 'skin/smallavatar/6000.png',
      imageFull: 'skin/full/6000.png',
      model3D: 'skin/model3d/6000.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'The Machine Gun',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 601,
      heroTypeId: 6,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/6001.png',
      imageSmallAvatar: 'skin/smallavatar/6001.png',
      imageFull: 'skin/full/6001.png',
      model3D: 'skin/model3d/6001.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Prison Breaker',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 602,
      heroTypeId: 6,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/6002.png',
      imageSmallAvatar: 'skin/smallavatar/6002.png',
      imageFull: 'skin/full/6002.png',
      model3D: 'skin/model3d/6002.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'Tackle',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 700,
      heroTypeId: 7,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/7000.png',
      imageSmallAvatar: 'skin/smallavatar/7000.png',
      imageFull: 'skin/full/7000.png',
      model3D: 'skin/model3d/7000.glb',
      scaleRatio: 1.5,
      cost: 1667,
      name: 'Forgotten Samurai',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 701,
      heroTypeId: 7,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/7001.png',
      imageSmallAvatar: 'skin/smallavatar/7001.png',
      imageFull: 'skin/full/7001.png',
      model3D: 'skin/model3d/7001.glb',
      scaleRatio: 1.5,
      cost: 1667,
      name: 'Star Batter',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 800,
      heroTypeId: 8,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/8000.png',
      imageSmallAvatar: 'skin/smallavatar/8000.png',
      imageFull: 'skin/full/8000.png',
      model3D: 'skin/model3d/8000.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'The Bomber',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 801,
      heroTypeId: 8,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/8001.png',
      imageSmallAvatar: 'skin/smallavatar/8001.png',
      imageFull: 'skin/full/8001.png',
      model3D: 'skin/model3d/8001.glb',
      scaleRatio: 1.2,
      cost: 1111,
      name: 'Scarecrow',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 900,
      heroTypeId: 9,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/9000.png',
      imageSmallAvatar: 'skin/smallavatar/9000.png',
      imageFull: 'skin/full/9000.png',
      model3D: 'skin/model3d/9000.glb',
      scaleRatio: 1.1,
      cost: 333,
      name: 'Outlaw Gangster',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 901,
      heroTypeId: 9,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/9001.png',
      imageSmallAvatar: 'skin/smallavatar/9001.png',
      imageFull: 'skin/full/9001.png',
      model3D: 'skin/model3d/9001.glb',
      scaleRatio: 1.1,
      cost: 333,
      name: 'Captain Pool',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 902,
      heroTypeId: 9,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/9002.png',
      imageSmallAvatar: 'skin/smallavatar/9002.png',
      imageFull: 'skin/full/9002.png',
      model3D: 'skin/model3d/9002.glb',
      scaleRatio: 1,
      cost: 333,
      name: 'Lunar New Year',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1000,
      heroTypeId: 10,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/10000.png',
      imageSmallAvatar: 'skin/smallavatar/10000.png',
      imageFull: 'skin/full/10000.png',
      model3D: 'skin/model3d/10000.glb',
      scaleRatio: 1.2,
      cost: 16667,
      name: 'The Duo Axes',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1001,
      heroTypeId: 10,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/10001.png',
      imageSmallAvatar: 'skin/smallavatar/10001.png',
      imageFull: 'skin/full/10001.png',
      model3D: 'skin/model3d/10001.glb',
      scaleRatio: 1.2,
      cost: 16667,
      name: 'Grand Slam',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1100,
      heroTypeId: 11,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/11000.png',
      imageSmallAvatar: 'skin/smallavatar/11000.png',
      imageFull: 'skin/full/11000.png',
      model3D: 'skin/model3d/11000.glb',
      scaleRatio: 1.2,
      cost: 1667,
      name: 'Wolffun Guitarist',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1101,
      heroTypeId: 11,
      heroRarity: 1,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/11001.png',
      imageSmallAvatar: 'skin/smallavatar/11001.png',
      imageFull: 'skin/full/11001.png',
      model3D: 'skin/model3d/11001.glb',
      scaleRatio: 1.2,
      cost: 3333,
      name: 'Academy Lead Singer',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1102,
      heroTypeId: 11,
      heroRarity: 1,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/11002.png',
      imageSmallAvatar: 'skin/smallavatar/11002.png',
      imageFull: 'skin/full/11002.png',
      model3D: 'skin/model3d/11002.glb',
      scaleRatio: 1.2,
      cost: 5556,
      name: 'Geisha',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1200,
      heroTypeId: 12,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/12000.png',
      imageSmallAvatar: 'skin/smallavatar/12000.png',
      imageFull: 'skin/full/12000.png',
      model3D: 'skin/model3d/12000.glb',
      scaleRatio: 1,
      cost: 16667,
      name: "Dynasty's Ranger",
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1201,
      heroTypeId: 12,
      heroRarity: 2,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/12001.png',
      imageSmallAvatar: 'skin/smallavatar/12001.png',
      imageFull: 'skin/full/12001.png',
      model3D: 'skin/model3d/12001.glb',
      scaleRatio: 1,
      cost: 55556,
      name: 'Lunar New Year',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 1202,
      heroTypeId: 12,
      heroRarity: 2,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/12002.png',
      imageSmallAvatar: 'skin/smallavatar/12002.png',
      imageFull: 'skin/full/12002.png',
      model3D: 'skin/model3d/12002.glb',
      scaleRatio: 1,
      cost: 55556,
      name: 'Elf Guardian',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1300,
      heroTypeId: 13,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/13000.png',
      imageSmallAvatar: 'skin/smallavatar/13000.png',
      imageFull: 'skin/full/13000.png',
      model3D: 'skin/model3d/13000.glb',
      scaleRatio: 1.3,
      cost: 16667,
      name: 'Rising Spirit',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1301,
      heroTypeId: 13,
      heroRarity: 2,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/13001.png',
      imageSmallAvatar: 'skin/smallavatar/13001.png',
      imageFull: 'skin/full/13001.png',
      model3D: 'skin/model3d/13001.glb',
      scaleRatio: 1.3,
      cost: 33333,
      name: 'Strelitzia',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1302,
      heroTypeId: 13,
      heroRarity: 2,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/13002.png',
      imageSmallAvatar: 'skin/smallavatar/13002.png',
      imageFull: 'skin/full/13002.png',
      model3D: 'skin/model3d/13002.glb',
      scaleRatio: 1.3,
      cost: 33333,
      name: 'YGG Phoenix',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1400,
      heroTypeId: 14,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/14000.png',
      imageSmallAvatar: 'skin/smallavatar/14000.png',
      imageFull: 'skin/full/14000.png',
      model3D: 'skin/model3d/14000.glb',
      scaleRatio: 1,
      cost: 1667,
      name: 'Protective Robot',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1401,
      heroTypeId: 14,
      heroRarity: 1,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/14001.png',
      imageSmallAvatar: 'skin/smallavatar/14001.png',
      imageFull: 'skin/full/14001.png',
      model3D: 'skin/model3d/14001.glb',
      scaleRatio: 1,
      cost: 5556,
      name: 'Count Meiko',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1402,
      heroTypeId: 14,
      heroRarity: 1,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/14002.png',
      imageSmallAvatar: 'skin/smallavatar/14002.png',
      imageFull: 'skin/full/14002.png',
      model3D: 'skin/model3d/14002.glb',
      scaleRatio: 0.8,
      cost: 5556,
      name: 'Ghost Captain',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 1500,
      heroTypeId: 15,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/15000.png',
      imageSmallAvatar: 'skin/smallavatar/15000.png',
      imageFull: 'skin/full/15000.png',
      model3D: 'skin/model3d/15000.glb',
      scaleRatio: 1.3,
      cost: 333,
      name: 'The Boss',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1501,
      heroTypeId: 15,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/15001.png',
      imageSmallAvatar: 'skin/smallavatar/15001.png',
      imageFull: 'skin/full/15001.png',
      model3D: 'skin/model3d/15001.glb',
      scaleRatio: 1.3,
      cost: 1111,
      name: 'Lunar New Year',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 1502,
      heroTypeId: 15,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/15002.png',
      imageSmallAvatar: 'skin/smallavatar/15002.png',
      imageFull: 'skin/full/15002.png',
      model3D: 'skin/model3d/15002.glb',
      scaleRatio: 1.3,
      cost: 1111,
      name: 'Big Santa',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1600,
      heroTypeId: 16,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/16000.png',
      imageSmallAvatar: 'skin/smallavatar/16000.png',
      imageFull: 'skin/full/16000.png',
      model3D: 'skin/model3d/16000.glb',
      scaleRatio: 1.3,
      cost: 1667,
      name: 'Outlaw Fighter',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1601,
      heroTypeId: 16,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/16001.png',
      imageSmallAvatar: 'skin/smallavatar/16001.png',
      imageFull: 'skin/full/16001.png',
      model3D: 'skin/model3d/16001.glb',
      scaleRatio: 1.3,
      cost: 1667,
      name: 'Lifeguard',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 1602,
      heroTypeId: 16,
      heroRarity: 1,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/16002.png',
      imageSmallAvatar: 'skin/smallavatar/16002.png',
      imageFull: 'skin/full/16002.png',
      model3D: 'skin/model3d/16002.glb',
      scaleRatio: 1.3,
      cost: 5556,
      name: 'Lunar New Year',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1603,
      heroTypeId: 16,
      heroRarity: 1,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/16003.png',
      imageSmallAvatar: 'skin/smallavatar/16003.png',
      imageFull: 'skin/full/16003.png',
      model3D: 'skin/model3d/16003.glb',
      scaleRatio: 1.3,
      cost: 5556,
      name: 'Golden Hand',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 1700,
      heroTypeId: 17,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/17000.png',
      imageSmallAvatar: 'skin/smallavatar/17000.png',
      imageFull: 'skin/full/17000.png',
      model3D: 'skin/model3d/17000.glb',
      scaleRatio: 1.3,
      cost: 1667,
      name: 'Mystery Mask',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1701,
      heroTypeId: 17,
      heroRarity: 1,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/17001.png',
      imageSmallAvatar: 'skin/smallavatar/17001.png',
      imageFull: 'skin/full/17001.png',
      model3D: 'skin/model3d/17001.glb',
      scaleRatio: 1.3,
      cost: 3333,
      name: 'Mystic Student',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1702,
      heroTypeId: 17,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/17002.png',
      imageSmallAvatar: 'skin/smallavatar/17002.png',
      imageFull: 'skin/full/17002.png',
      model3D: 'skin/model3d/17002.glb',
      scaleRatio: 1.3,
      cost: 3333,
      name: 'Marvelous Whistle',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 1800,
      heroTypeId: 18,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/18000.png',
      imageSmallAvatar: 'skin/smallavatar/18000.png',
      imageFull: 'skin/full/18000.png',
      model3D: 'skin/model3d/18000.glb',
      scaleRatio: 1.1,
      cost: 1667,
      name: 'The General',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1801,
      heroTypeId: 18,
      heroRarity: 1,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/18001.png',
      imageSmallAvatar: 'skin/smallavatar/18001.png',
      imageFull: 'skin/full/18001.png',
      model3D: 'skin/model3d/18001.glb',
      scaleRatio: 1.1,
      cost: 3333,
      name: 'Bounty Hunter',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1900,
      heroTypeId: 19,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/19000.png',
      imageSmallAvatar: 'skin/smallavatar/19000.png',
      imageFull: 'skin/full/19000.png',
      model3D: 'skin/model3d/19000.glb',
      scaleRatio: 1,
      cost: 16667,
      name: 'Violet Blossom',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 1901,
      heroTypeId: 19,
      heroRarity: 2,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/19001.png',
      imageSmallAvatar: 'skin/smallavatar/19001.png',
      imageFull: 'skin/full/19001.png',
      model3D: 'skin/model3d/19001.glb',
      scaleRatio: 1.1,
      cost: 55556,
      name: 'Lunar New Year',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 1902,
      heroTypeId: 19,
      heroRarity: 2,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/19002.png',
      imageSmallAvatar: 'skin/smallavatar/19002.png',
      imageFull: 'skin/full/19002.png',
      model3D: 'skin/model3d/19002.glb',
      scaleRatio: 1.1,
      cost: 55556,
      name: 'Glorious Rabbittail',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 2000,
      heroTypeId: 20,
      heroRarity: 1,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/20000.png',
      imageSmallAvatar: 'skin/smallavatar/20000.png',
      imageFull: 'skin/full/20000.png',
      model3D: 'skin/model3d/20000.glb',
      scaleRatio: 1,
      cost: 1667,
      name: 'Ammunition Man',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2100,
      heroTypeId: 21,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/21000.png',
      imageSmallAvatar: 'skin/smallavatar/21000.png',
      imageFull: 'skin/full/21000.png',
      model3D: 'skin/model3d/21000.glb',
      scaleRatio: 1.1,
      cost: 16667,
      name: 'Martial Art Master',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2101,
      heroTypeId: 21,
      heroRarity: 2,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/21001.png',
      imageSmallAvatar: 'skin/smallavatar/21001.png',
      imageFull: 'skin/full/21001.png',
      model3D: 'skin/model3d/21001.glb',
      scaleRatio: 1.1,
      cost: 33333,
      name: 'Fire Kick',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2200,
      heroTypeId: 22,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/22000.png',
      imageSmallAvatar: 'skin/smallavatar/22000.png',
      imageFull: 'skin/full/22000.png',
      model3D: 'skin/model3d/22000.glb',
      scaleRatio: 1.1,
      cost: 16667,
      name: 'Raging Gorilla',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2201,
      heroTypeId: 22,
      heroRarity: 2,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/22001.png',
      imageSmallAvatar: 'skin/smallavatar/22001.png',
      imageFull: 'skin/full/22001.png',
      model3D: 'skin/model3d/22001.glb',
      scaleRatio: 1.1,
      cost: 16667,
      name: 'Godz-rilla',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2300,
      heroTypeId: 23,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/23000.png',
      imageSmallAvatar: 'skin/smallavatar/23000.png',
      imageFull: 'skin/full/23000.png',
      model3D: 'skin/model3d/23000.glb',
      scaleRatio: 1.1,
      cost: 333,
      name: 'The Forgotten Noble',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2301,
      heroTypeId: 23,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/23001.png',
      imageSmallAvatar: 'skin/smallavatar/23001.png',
      imageFull: 'skin/full/23001.png',
      model3D: 'skin/model3d/23001.glb',
      scaleRatio: 1,
      cost: 333,
      name: 'Reindeer',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2400,
      heroTypeId: 24,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/24000.png',
      imageSmallAvatar: 'skin/smallavatar/24000.png',
      imageFull: 'skin/full/24000.png',
      model3D: 'skin/model3d/24000.glb',
      scaleRatio: 1.1,
      cost: 333,
      name: 'The Baby',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2401,
      heroTypeId: 24,
      heroRarity: 0,
      skinRarity: 2,
      imageAvatar: 'skin/avatar/24001.png',
      imageSmallAvatar: 'skin/smallavatar/24001.png',
      imageFull: 'skin/full/24001.png',
      model3D: 'skin/model3d/24001.glb',
      scaleRatio: 1,
      cost: 333,
      name: 'Penguin',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2402,
      heroTypeId: 24,
      heroRarity: 0,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/24002.png',
      imageSmallAvatar: 'skin/smallavatar/24002.png',
      imageFull: 'skin/full/24002.png',
      model3D: 'skin/model3d/24002.glb',
      scaleRatio: 1,
      cost: 333,
      name: 'Boomby Shark',
      isActive: false,
      isSellNonNFTShop: false,
    },
    {
      id: 2500,
      heroTypeId: 25,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/25000.png',
      imageSmallAvatar: 'skin/smallavatar/25000.png',
      imageFull: 'skin/full/25000.png',
      model3D: 'skin/model3d/25000.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'Cat Ninja',
      isListMarket: true,
      isActive: true,
      isSellNonNFTShop: true,
    },
    {
      id: 2501,
      heroTypeId: 25,
      heroRarity: 2,
      skinRarity: 1,
      imageAvatar: 'skin/avatar/25001.png',
      imageSmallAvatar: 'skin/smallavatar/25001.png',
      imageFull: 'skin/full/25001.png',
      model3D: 'skin/model3d/25001.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'Glorious Royalguard',
      isActive: true,
      isSellNonNFTShop: false,
    },
    {
      id: 2600,
      heroTypeId: 26,
      heroRarity: 2,
      skinRarity: 0,
      imageAvatar: 'skin/avatar/26000.png',
      imageSmallAvatar: 'skin/smallavatar/26000.png',
      imageFull: 'skin/full/26000.png',
      model3D: 'skin/model3d/26000.glb',
      scaleRatio: 1.2,
      cost: 333,
      name: 'Gourmet Chef',
      isActive: true,
      isSellNonNFTShop: false,
    },
  ],
};
export const initState: InitState = {
  dashboardState: initDashboardState,
  buyTabState: initBuyTabState,
};
