import {StyleSheet} from 'react-native';
import {normalize} from '../../../../utils/utils';

const styles = StyleSheet.create({
  root: {
    position: 'relative',
    height: normalize(255),
    width: normalize(160),
  },
  avatar: {
    position: 'absolute',
    top: normalize(32),
    left: normalize(21),
    width: normalize(117),
    height: normalize(117),
    zIndex: 1,
  },
  avatarSpaceship: {
    width: normalize(159),
    top: 0,
    left: 0,
    height: normalize(230),
  },
  bgItem: {
    position: 'absolute',
    width: '100%',
    height: normalize(231),
    bottom: 0,
    left: 0,
  },
  contentTop: {
    position: 'absolute',
    right: normalize(4),
    top: 0,
    display: 'flex',
    gap: normalize(8),
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icTrophy: {
    width: normalize(24),
    height: normalize(24),
  },
  level: {
    position: 'relative',
    width: normalize(24),
    height: normalize(24),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bgLevel: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '100%',
    height: '100%',
  },
  valueLevel: {
    fontSize: normalize(14),
    color: 'white',
    fontWeight: '700',
    lineHeight: normalize(20),
    marginBottom: normalize(4),
  },
  icRole: {
    width: normalize(24),
    height: normalize(13.5),
  },
  content: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 2,
  },
  itemInfo: {
    paddingVertical: normalize(12),
    paddingLeft: normalize(18),
    paddingRight: normalize(8),
    marginTop: normalize(6),
  },
  info: {
    position: 'relative',
  },
  borderRight: {
    position: 'absolute',
    width: normalize(6),
    height: '100%',
    top: 0,
    left: normalize(-8),
    backgroundColor: '#00C2FF',
  },
  nameSkin: {
    fontSize: normalize(8),
    lineHeight: normalize(12),
    color: '#00F0FF',
    fontWeight: '600',
  },
  name: {
    fontSize: normalize(12),
    lineHeight: normalize(17.25),
    color: 'white',
    fontWeight: '700',
  },
  flexSpaceBetween: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  releasedTitle: {
    fontSize: normalize(8),
    fontWeight: '400',
    color: 'white',
  },
  textFontSize9: {
    fontSize: normalize(9),
    fontWeight: '400',
    color: 'white',
    lineHeight: normalize(13.27),
  },
  traddingEvent: {
    width: '100%',
    backgroundColor: '#2EF2FE',
    paddingVertical: normalize(2),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  traddingEventTitle: {
    fontSize: normalize(9),
    fontWeight: '700',
    color: '#000D54',
    lineHeight: normalize(11.25),
  },
  statsItem: {
    backgroundColor: '#1B1444',
    paddingLeft: normalize(21),
    paddingRight: normalize(8),
    paddingVertical: normalize(8),
    display: 'flex',
    borderBottomLeftRadius: normalize(4),
    borderBottomRightRadius: normalize(4),
    overflow: 'hidden',
    gap: normalize(3),
  },
  battleCap: {
    fontSize: normalize(10),
    lineHeight: normalize(14.6),
    fontWeight: '500',
    color: '#10FF00',
  },
  price: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    gap: normalize(4),
    textAlign: 'right',
  },
  iconPrice: {
    width: normalize(12),
    height: normalize(12),
  },
  valuePrice: {
    fontSize: normalize(12),
    fontWeight: '700',
    color: '#FFE076',
  },
  typePrice: {
    fontSize: normalize(8),
    color: '#FFE076',
    fontWeight: '400',
  },
  priceDolaValue: {
    fontSize: normalize(8),
    lineHeight: normalize(10),
    color: '#C6C9DC',
    textAlign: 'right',
    marginTop: normalize(8),
  },
});

export default styles;
